services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "14250:14250"
      - "4317:4317"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: otel-collector
    command: ["--config=/etc/otel/collector.yml"]
    volumes:
      - ${OTEL_COLLECTOR_CONFIG}:/etc/otel/collector.yml
    ports:
      - "4318:4318"
    depends_on:
      - jaeger
