# 데이터 베이스
postgres:
  host: localhost
  port: 5432
  user: root
  password: 1234
  name: dev
  sslMode: disable
  maxOpenConns: 10
  maxIdleConns: 5

# 로깅
log:
  level: debug

# CORS
cors:
  allowOrigins:
    - http://localhost:3000
    - http://localhost:5173
  allowMethods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowHeaders:
    - Content-Type
    - Authorization
  allowCredentials: true

#Cookie
cookie:
  name: SH_REFRESH
  path: /
  httpOnly: true
  secure: false
  sameSite: Lax
  maxAge: 14

# OpenTelemetry
observability:
  enabled: true
  serviceName: myapp-dev
  otlpEndpoint: localhost:4318
  sampleRatio: 1
